# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Itunes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage', '~> 5.0'

  # Pods for Itunes

  target 'ItunesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
